# Generated by Django 5.1.3 on 2024-11-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='uuid',
            field=models.CharField(max_length=200),
        ),
    ]
